version: '2'
services:
  php:
    build:
      context: php
      args:
        UID: ${UID}
        GID: ${GID}
    restart: always
    volumes:
      - ./src:/src:z
      - ./data/repo:/var/repo:z
      - ./etc/www.conf:/etc/php7/php-fpm.d/www.conf:z
      - ./etc/local.json:/src/phabricator/conf/local/local.json:z
    networks:
      - phabricator
    depends_on:
      - aphlict
  phd:
    build:
      context: php
      args:
        UID: ${UID}
        GID: ${GID}
    restart: always
    volumes:
      - ./src:/src:z
      - ./data/repo:/var/repo:z
      - ./etc/www.conf:/etc/php7/php-fpm.d/www.conf:z
      - ./etc/local.json:/src/phabricator/conf/local/local.json:z
    command: ["/usr/local/bin/phd"]
    networks:
      - phabricator
    depends_on:
      - aphlict
  aphlict:
    build:
      context: php
      args:
        UID: ${UID}
        GID: ${GID}
    restart: always
    volumes:
      - ./src:/src:z
      - ./etc/local.json:/src/phabricator/conf/local/local.json:z
      - ./etc/aphlict.json:/etc/aphlict.json:z
    command: ["/usr/local/bin/aphlict"]
    networks:
      - phabricator
#  mysql:
#    build:
#      context: mysql
#      args:
#        UID: ${UID}
#        GID: ${GID}
#    restart: always
#    volumes:
#      - ./data/mysql:/var/lib/mysql:z
#      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
#    networks:
#      - phabricator
#    container_name: mysql
  mysql2:
      image: mysql:5.7.23
      command: --max_allowed_packet=20971520
      # 配置环境变量
      environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: notsosecret
          MYSQL_ROOT_HOST: "%"
      networks:
          - phabricator
      ports:
          - 3301:3306
      volumes:
          # mysql 配置文件
          - ./etc/mysql/conf.d:/etc/mysql/conf.d:ro
          # mysql 配置文件
          - ./etc/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d:ro
#      volumes:
#          # mysql 配置文件
#          - ${LOCAL_STOARGE_PATH}/mysql/conf.d:/etc/mysql/conf.d:ro,cached
#          # mysql 配置文件
#          - ${LOCAL_STOARGE_PATH}/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d:ro,cached
#          # mysql 数据库
#          - ${LOCAL_STOARGE_PATH}/mysql/db:/var/lib/mysql
#          # mysql 日志
#          - ${LOCAL_STOARGE_PATH}/mysql/logs:/var/log/mysql
      container_name: mysql2
  nginx:
    build: nginx
    restart: always
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:z
      - ./nginx:/var/log/nginx
      - ./src:/src:z
    networks:
      - phabricator
    ports:
      - ${PORT}:8080
    depends_on:
      - php
      - aphlict
    container_name: "compose-nginx"
networks:
  phabricator:
    external: false
